export const languages = Object.freeze({
  en: 'English',
  ml: 'Malayalam',
  manglish: 'Manglish',
  sw: 'Kiswahili',
});

export const stickers = Object.freeze({
  // ==========================================
  // 💖 Love & Romance
  // ==========================================
  love: '💚',
  red_heart: '❤️',
  sparkle_heart: '💖',
  two_hearts: '💕',
  heart_eyes: '😍',
  kiss: '😘',
  rose: '🌹',
  fire: '🔥',
  pink_heart: '🩷',
  heart_kiss: '💏',
  heart_with_arrow: '💘',
  heart_on_fire: '❤️‍🔥',
  revolving_hearts: '💞',
  love_letter: '💌',
  ring: '💍',
  sparkles: '✨',
  bouquet: '💐',
  teddy_bear: '🧸',
  holding_hands: '🧑‍🤝‍🧑',
  couple_kiss: '👩‍❤️‍💋‍👨',
  melting_face: '🫠',
  blushing_smile: '😊',
  cuddle: '🫂',
  heart_ribbon: '💝',
  love_eyes_cat: '😻',

  // ==========================================
  // 😂 Moods & Reactions
  // ==========================================
  hello: '👋',
  thanks: '🙏',
  hug: '🫂',
  bff: '🤝',
  celebrate: '🎉',
  laugh: '😂',
  wow: '🤩',
  yes: '🙌',
  peace: '✌️',
  cheers: '🥂',
  crying_laughing: '🤣',
  mind_blown: '🤯',
  cool: '😎',
  partying_face: '🥳',
  rofl: '😆',
  in_love: '🥰',
  shy: '🥺',
  winking: '😉',
  drooling: '🤤',
  pleading: '🥹',
  salute: '🫡',
  mind_blown_spark: '⚡',
  eyes: '👀',
  speechless: '😶',
  facepalm: '🤦',
  shrug: '🤷',
  one_hundred: '💯',
  high_five: '✋',
  praying: '🤲',
  clap: '👏',
  thinking: '🤔',
  clinking_glasses: '🍻',
  tears_of_joy: '🥲',
  yawn: '🥱',
  wink_tongue: '😜',
  fire_eyes: '🔥',

  // ==========================================
  // 🌴 Kerala Food & Vibes
  // ==========================================
  parotta: '🥞',
  chaya: '☕',
  sadhya: '🍛',
  meen_curry: '🐟',
  pazham_pori: '🍌',
  biryani: '🍲',
  payasam: '🍨',
  elephant: '🐘',
  coconut_tree: '🌴',
  snake_boat: '🚣',
  kerala_lamp: '🪔',
  masala_dosa: '🥘',
  appam: '🫓',
  puttu: '🍚',
  kattan_chaya: '🍵',
  karimeen: '🐠',
  mango_achar: '🥭',
  banana_chips: '🥨',
  jackfruit: '🍈',
  peacock: '🦚',
  monsoon_rain: '🌧️',

  // ==========================================
  // 🇰🇪 Kenyan Food & Vibes
  // ==========================================
  ugali: '🥣',
  nyama_choma: '🥩',
  sukuma_wiki: '🥬',
  mandazi: '🍩',
  chapati: '🫓',
  samosa: '🥟',
  kenyan_tea: '🫖',
  lion: '🦁',
  giraffe: '🦒',
  zebra: '🦓',
  safari: '🚙',
  african_drum: '🪘',
  shield: '🛡️',
  coffee_cup: '☕',
  sun_savannah: '🌅',
  acacia_tree: '🌳',

  // ==========================================
  // 🐾 Cute Animals & Pets
  // ==========================================
  puppy: '🐶',
  kitten: '🐱',
  panda: '🐼',
  bunny: '🐰',
  bear: '🐻',
  penguin: '🐧',
  otter: '🦦',
  fox: '🦊',
  koala: '🐨',
  butterfly: '🦋',
  dove: '🕊️',
  dolphin: '🐬',
  duck: '🦆',
  unicorn: '🦄',
  chick: '🐥',
  hamster: '🐹',
  sloth: '🦥',

  // ==========================================
  // 🍔 Favorites, Street Food & Drinks
  // ==========================================
  burger: '🍔',
  pizza: '🍕',
  chicken: '🍗',
  mutton: '🍖',
  prawns: '🦐',
  crab: '🦀',
  apple: '🍎',
  orange: '🍊',
  mango: '🥭',
  coconut: '🥥',
  corn: '🌽',
  beans: '🫘',
  okra: '🫛',
  french_fries: '🍟',
  hotdog: '🌭',
  ice_cream: '🍦',
  donut: '🍩',
  cake: '🎂',
  chocolate: '🍫',
  popcorn: '🍿',
  boba_tea: '🧋',
  fresh_juice: '🧃',
  cookie: '🍪',
  taco: '🌮',
  avocado: '🥑',
  strawberry: '🍓',
  watermelon: '🍉',
  croissant: '🥐',

  // ==========================================
  // 🎉 Celebrations, Magic & Fun
  // ==========================================
  party_popper: '🎊',
  balloon: '🎈',
  fireworks: '🎆',
  sparkler: '🎇',
  magic_wand: '🪄',
  crystal_ball: '🔮',
  rainbow: '🌈',
  sunflower: '🌻',
  moon: '🌙',
  star_glow: '⭐',
  music_notes: '🎶',
  guitar: '🎸',
  headphones: '🎧',
  game_controller: '🎮',
  trophy: '🏆',
  gem: '💎',
  lightning: '⚡',
  rocket: '🚀',
  folded_hands: '🙏',
});

export const stickerCategories = Object.freeze({
  all: { label: 'All', icon: '🌟' },
  love: {
    label: 'Love',
    icon: '💖',
    keys: [
      'love',
      'red_heart',
      'sparkle_heart',
      'two_hearts',
      'heart_eyes',
      'kiss',
      'rose',
      'fire',
      'pink_heart',
      'heart_kiss',
      'heart_with_arrow',
      'heart_on_fire',
      'revolving_hearts',
      'love_letter',
      'ring',
      'sparkles',
      'bouquet',
      'teddy_bear',
      'holding_hands',
      'couple_kiss',
      'melting_face',
      'blushing_smile',
      'cuddle',
      'heart_ribbon',
      'love_eyes_cat',
    ],
  },
  reactions: {
    label: 'Moods',
    icon: '😂',
    keys: [
      'hello',
      'thanks',
      'hug',
      'bff',
      'celebrate',
      'laugh',
      'wow',
      'yes',
      'peace',
      'cheers',
      'crying_laughing',
      'mind_blown',
      'cool',
      'partying_face',
      'rofl',
      'in_love',
      'shy',
      'winking',
      'drooling',
      'pleading',
      'salute',
      'mind_blown_spark',
      'eyes',
      'speechless',
      'facepalm',
      'shrug',
      'one_hundred',
      'high_five',
      'praying',
      'clap',
      'thinking',
      'clinking_glasses',
      'tears_of_joy',
      'yawn',
      'wink_tongue',
      'fire_eyes',
    ],
  },
  kerala: {
    label: 'Kerala',
    icon: '🌴',
    keys: [
      'parotta',
      'chaya',
      'sadhya',
      'meen_curry',
      'pazham_pori',
      'biryani',
      'payasam',
      'elephant',
      'coconut_tree',
      'snake_boat',
      'kerala_lamp',
      'masala_dosa',
      'appam',
      'puttu',
      'kattan_chaya',
      'karimeen',
      'mango_achar',
      'banana_chips',
      'jackfruit',
      'peacock',
      'monsoon_rain',
    ],
  },
  kenya: {
    label: 'Kenya',
    icon: '🇰🇪',
    keys: [
      'ugali',
      'nyama_choma',
      'sukuma_wiki',
      'mandazi',
      'chapati',
      'samosa',
      'kenyan_tea',
      'lion',
      'giraffe',
      'zebra',
      'safari',
      'african_drum',
      'shield',
      'coffee_cup',
      'sun_savannah',
      'acacia_tree',
    ],
  },
  animals: {
    label: 'Cute',
    icon: '🐾',
    keys: [
      'puppy',
      'kitten',
      'panda',
      'bunny',
      'bear',
      'penguin',
      'otter',
      'fox',
      'koala',
      'butterfly',
      'dove',
      'dolphin',
      'duck',
      'unicorn',
      'chick',
      'hamster',
      'sloth',
    ],
  },
  food: {
    label: 'Food',
    icon: '🍔',
    keys: [
      'burger',
      'pizza',
      'chicken',
      'mutton',
      'prawns',
      'crab',
      'apple',
      'orange',
      'mango',
      'coconut',
      'corn',
      'beans',
      'okra',
      'french_fries',
      'hotdog',
      'ice_cream',
      'donut',
      'cake',
      'chocolate',
      'popcorn',
      'boba_tea',
      'fresh_juice',
      'cookie',
      'taco',
      'avocado',
      'strawberry',
      'watermelon',
      'croissant',
    ],
  },
  party: {
    label: 'Party',
    icon: '🎉',
    keys: [
      'party_popper',
      'balloon',
      'fireworks',
      'sparkler',
      'magic_wand',
      'crystal_ball',
      'rainbow',
      'sunflower',
      'moon',
      'star_glow',
      'music_notes',
      'guitar',
      'headphones',
      'game_controller',
      'trophy',
      'gem',
      'lightning',
      'rocket',
      'folded_hands',
    ],
  },
});
