export const FEATURE_LANGUAGES = ['en', 'ml', 'manglish', 'sw'];
export const normalizeFeatureText = text => typeof text === 'string' ? text.replace(/\s+/g, ' ').trim() : '';

export function receiverMessageText(message, language) {
  if (message.deleted_at) return null;
  const indexed = message.translations?.[language];
  const candidate = indexed ? { ...indexed, language: indexed.language || language } : message.translation;
  return candidate?.status === 'ready' && candidate.language === language && typeof candidate.text === 'string' && candidate.text.trim()
    ? candidate.text : null;
}

// The toolkit is available in every supported language without a translation service.
// English remains the navigation language. Only feature copy goes through this catalogue.
export const featureCopy = {
  'Realtime games with {name}': ['{name}-നൊപ്പം തത്സമയ കളികൾ', '{name}-noppam thalsamaya kalikal', 'Michezo mubashara pamoja na {name}'],
  'Ice cream / Sweets 🍨': ['ഐസ്ക്രീം / മധുരം 🍨', 'Ice cream / Madhuram 🍨', 'Aiskrimu / Pipi 🍨'],
  'Biryani / Spicy food 🍛': ['ബിരിയാണി / എരിവുള്ള ഭക്ഷണം 🍛', 'Biriyani / Erivulla bhakshanam 🍛', 'Biryani / Chakula chenye viungo 🍛'],
  'Chai / Coffee ☕': ['ചായ / കാപ്പി ☕', 'Chaya / Kappi ☕', 'Chai / Kahawa ☕'],
  'Chocolates 🍫': ['ചോക്ലേറ്റുകൾ 🍫', 'Chocolateukal 🍫', 'Chokoleti 🍫'],
  'Pure butterflies in the stomach 🦋': ['മനസ്സിൽ ഒരു ആവേശം 🦋', 'Manassil oru avesham 🦋', 'Msisimko wa moyoni 🦋'],
  'Instant sense of peace & comfort 🕊️': ['ഉടനെയുള്ള സമാധാനവും ആശ്വാസവും 🕊️', 'Udaneyulla samadhanavum ashwasavum 🕊️', 'Amani na faraja mara moja 🕊️'],
  'Could not stop smiling 😊': ['ചിരി നിർത്താനായില്ല 😊', 'Chiri nirthanayilla 😊', 'Sikuweza kuacha kutabasamu 😊'],
  'Fell in love right away 💖': ['ആദ്യ നിമിഷം തന്നെ പ്രണയം 💖', 'Aadya nimisham thanne pranayam 💖', 'Nilipenda mara moja 💖'],
  'Quality Time': ['ഒരുമിച്ചുള്ള സമയം', 'Orumichulla samayam', 'Muda wa pamoja'],
  'Words of Affirmation': ['സ്നേഹവാക്കുകൾ', 'Snehavakkukal', 'Maneno ya kuthamini'],
  'Physical Touch & Hugs': ['സ്പർശനവും ആലിംഗനവും', 'Sparshanavum alinganavum', 'Mguso na kumbatio'],
  'Acts of Service': ['കരുതലും സഹായവും', 'Karuthalum sahayavum', 'Vitendo vya kujali'],
  'മഴയുള്ള രാത്രിയിൽ ബ്ലാങ്കറ്റിൽ സിനിമ കാണൽ 🌧️': ['മഴയുള്ള രാത്രിയിൽ ബ്ലാങ്കറ്റിൽ സിനിമ കാണൽ 🌧️', 'Mazhayulla rathriyil blanketil cinema kanal 🌧️', 'Kutazama filamu chini ya blanketi usiku wa mvua 🌧️'],
  'ബീച്ചിൽ സൂര്യാസ്തമയ നടപ്പ് 🌅': ['ബീച്ചിൽ സൂര്യാസ്തമയ നടപ്പ് 🌅', 'Beachil sooryasthamaya nadappu 🌅', 'Kutembea ufukweni wakati wa machweo 🌅'],
  'മിഡ്‌നൈറ്റ് ലോങ് ഡ്രൈവ് & മ്യൂസിക് 🚗': ['അർധരാത്രിയിലെ യാത്രയും പാട്ടും 🚗', 'Ardharathriyile yathrayum pattum 🚗', 'Safari ya usiku wa manane na muziki 🚗'],
  'വീട്ടിൽ ഉണ്ടാക്കിയ ക്യാൻഡിൽ ലൈറ്റ് ഡിന്നർ 🕯️': ['വീട്ടിലെ മെഴുകുതിരി വെളിച്ചത്തിലെ ഭക്ഷണം 🕯️', 'Veettile mezhukuthiri velichathile bhakshanam 🕯️', 'Chakula cha nyumbani kwa mwanga wa mishumaa 🕯️'],
  'Make a little time for {name}. Pick something to do together.': ['{name}-നൊപ്പം കുറച്ച് സമയം ചെലവഴിക്കാം. ഒന്നിച്ച് ചെയ്യാൻ എന്തെങ്കിലും തിരഞ്ഞെടുക്കൂ.', '{name}-noppam kurachu samayam chelavazhikkam. Onnichu cheyyan enthenkilum thiranjedukkoo.', 'Tenga muda kidogo kwa {name}. Chagua jambo la kufanya pamoja.'],
  'A little space for you and {name}. For the big days, and the beautifully ordinary ones.': ['നിങ്ങൾക്കും {name}-നും ഒരു ചെറിയ ഇടം. വലിയ ദിവസങ്ങൾക്കും മനോഹരമായ സാധാരണ ദിവസങ്ങൾക്കും.', 'Ningalkkum {name}-num oru cheriya idam. Valiya divasangalkkum manoharamaya sadharana divasangalkkum.', 'Nafasi ndogo kwako na {name}. Kwa siku kubwa na siku nzuri za kawaida.'],
  'Your inside jokes, shared playlists, and everyday check-ins belong here.': ['നിങ്ങളുടെ തമാശകൾക്കും പാട്ടുകൾക്കും ദിവസേനയുള്ള വിശേഷങ്ങൾക്കും ഒരിടം.', 'Ningalude thamashakalkkum pattukalkkum divasenayulla visheshangalkkum oridam.', 'Utani wenu, nyimbo mnazoshiriki na hali zenu za kila siku zina nafasi hapa.'],
  'Every good story starts with a hello.': ['എല്ലാ നല്ല കഥയും ഒരു ഹലോയിൽ തുടങ്ങുന്നു.', 'Ella nalla kathayum oru helloyil thudangunnu.', 'Kila hadithi nzuri huanza na salamu.'],
  'Select a conversation to unlock activities, or find your people.': ['പ്രവർത്തനങ്ങൾ തുടങ്ങാൻ ഒരു ചാറ്റ് തിരഞ്ഞെടുക്കൂ, അല്ലെങ്കിൽ സുഹൃത്തുക്കളെ കണ്ടെത്തൂ.', 'Pravarthanangal thudangan oru chat thiranjedukkoo, allenkil suhruthukkale kandethoo.', 'Chagua mazungumzo kuanza shughuli au tafuta marafiki zako.'],
  'For the people who feel like home. Distance has nothing on a friendship like this.': ['വീടുപോലെ തോന്നുന്ന സുഹൃത്തുക്കൾക്കായി. ഈ സൗഹൃദത്തിന് ദൂരം തടസ്സമല്ല.', 'Veedupole thonnunna suhruthukkalkkayi. Ee sauhridathinu dooram thadassamalla.', 'Kwa watu wanaokufanya ujisikie nyumbani. Umbali hauwezi kuvunja urafiki huu.'],
  'Show up. Laugh loud.': ['കൂടെ നിൽക്കൂ. മനസ്സറിഞ്ഞു ചിരിക്കൂ.', 'Koode nilkkoo. Manassarinju chirikkoo.', 'Kuwa karibu. Cheka kwa furaha.'],
  'Stay in each other’s corner.': ['എപ്പോഴും പരസ്പരം കൂടെ നിൽക്കൂ.', 'Eppozhum parasparam koode nilkkoo.', 'Simameni pamoja kila wakati.'],
  'THE RIDE-OR-DIE CLUB': ['എന്തിനും കൂടെ നിൽക്കുന്ന സൗഹൃദം', 'Enthinum koode nilkkunna sauhridam', 'Marafiki katika hali zote'],
  'How well do you know me?': ['നിങ്ങൾക്ക് എന്നെ എത്രത്തോളം അറിയാം?', 'Ningalkku enne ethratholam ariyam?', 'Unanijua vizuri kiasi gani?'],
  'Our Playroom 🎮💖': ['നമ്മുടെ കളിമുറി 🎮💖', 'Nammude kalimuri 🎮💖', 'Chumba chetu cha michezo 🎮💖'],
  'Love Trivia 🎯': ['സൗഹൃദ ചോദ്യങ്ങൾ 🎯', 'Sauhrida chodyangal 🎯', 'Maswali ya urafiki 🎯'],
  'Truth / Dare 🔥': ['സത്യം / ധൈര്യം 🔥', 'Sathyam / Dhairyam 🔥', 'Ukweli / Changamoto 🔥'],
  'Would You Rather? 🤔': ['ഏത് തിരഞ്ഞെടുക്കും? 🤔', 'Ethu thiranjedukkum? 🤔', 'Ungechagua nini? 🤔'],
  'Truth 💭': ['സത്യം 💭', 'Sathyam 💭', 'Ukweli 💭'],
  'Dare 🔥': ['ധൈര്യം 🔥', 'Dhairyam 🔥', 'Changamoto 🔥'],
  'Shuffle Next': ['മറ്റൊരു ചോദ്യം', 'Mattoru chodyam', 'Swali lingine'],
  'Share to Chat': ['ചാറ്റിൽ പങ്കിടുക', 'Chatil pankiduka', 'Shiriki kwenye mazungumzo'],
  'Send to Chat': ['ചാറ്റിൽ അയക്കുക', 'Chatil ayakkuka', 'Tuma kwenye mazungumzo'],
  'Every game together is a sweet new memory.': ['ഒരുമിച്ചുള്ള ഓരോ കളിയും ഒരു പുതിയ ഓർമ്മയാണ്.', 'Orumichulla oro kaliyum oru puthiya ormayanu.', 'Kila mchezo pamoja ni kumbukumbu mpya nzuri.'],
  'Question of the Day': ['ഇന്നത്തെ ചോദ്യം', 'Innathe chodyam', 'Swali la siku'],
  "Today's Prompt": ['ഇന്നത്തെ ചോദ്യം', 'Innathe chodyam', 'Swali la leo'],
  'Selected Prompt': ['തിരഞ്ഞെടുത്ത ചോദ്യം', 'Thiranjedutha chodyam', 'Swali lililochaguliwa'],
  'Our Memory Journal': ['നമ്മുടെ ഓർമ്മപ്പുസ്തകം', 'Nammude ormappusthakam', 'Daftari letu la kumbukumbu'],
  'History': ['മുൻ വിശേഷങ്ങൾ', 'Mun visheshangal', 'Historia'],
  'Write your answer': ['നിങ്ങളുടെ ഉത്തരം എഴുതൂ', 'Ningalude utharam ezhuthoo', 'Andika jibu lako'],
  'Save My Answer': ['എന്റെ ഉത്തരം സൂക്ഷിക്കുക', 'Ente utharam sookshikkuka', 'Hifadhi jibu langu'],
  'Your Answer': ['നിങ്ങളുടെ ഉത്തരം', 'Ningalude utharam', 'Jibu lako'],
  'Their Answer': ['അവരുടെ ഉത്തരം', 'Avarude utharam', 'Jibu lao'],
  'Answer': ['ഉത്തരം', 'Utharam', 'Jibu'],
  'Both of you answered with your heart. Here is what you both wrote:': ['രണ്ടുപേരും മനസ്സിൽ നിന്ന് ഉത്തരം പറഞ്ഞു. നിങ്ങളുടെ ഉത്തരങ്ങൾ ഇതാ:', 'Randuperum manassil ninnu utharam paranju. Ningalude utharangal itha:', 'Nyote mmejibu kutoka moyoni. Haya ndiyo majibu yenu:'],
  'Unfolding today’s special question... 💭': ['ഇന്നത്തെ ചോദ്യം തുറക്കുന്നു... 💭', 'Innathe chodyam thurakkunnu... 💭', 'Tunafungua swali maalumu la leo... 💭'],
  'Ideas / സൂചനകൾ:': ['സൂചനകൾ:', 'Soochanakal:', 'Mawazo:'],
  'Listen Together': ['ഒരുമിച്ച് കേൾക്കാം', 'Orumichu kelkkam', 'Sikilizeni pamoja'],
  'Play': ['പ്ലേ ചെയ്യുക', 'Play cheyyuka', 'Cheza'],
  'Pause': ['നിർത്തിവയ്ക്കുക', 'Nirthivaykkuka', 'Sitisha'],
  'Stop': ['നിർത്തുക', 'Nirthuka', 'Simamisha'],
  'Volume': ['ശബ്ദത്തിന്റെ അളവ്', 'Shabdathinte alavu', 'Sauti'],
  'Playlist': ['പാട്ടുകളുടെ പട്ടിക', 'Pattukalude pattika', 'Orodha ya nyimbo'],
  'Watch Together': ['ഒന്നിച്ച് കാണാം', 'Onnichu kanam', 'Tazameni pamoja'],
  'Now Playing': ['ഇപ്പോൾ പ്ലേ ചെയ്യുന്നത്', 'Ippol play cheyyunnathu', 'Inachezwa sasa'],
  'Sync': ['ഒത്തുചേർക്കുക', 'Othucherkuka', 'Sawazisha'],
  'Sync Now': ['ഇപ്പോൾ ഒത്തുചേർക്കുക', 'Ippol othucherkuka', 'Sawazisha sasa'],
  'Join': ['ചേരുക', 'Cheruka', 'Jiunge'],
  'Invite': ['ക്ഷണിക്കുക', 'Kshanikkuka', 'Alika'],
  'Leave': ['പുറത്തുകടക്കുക', 'Purathukadakkuka', 'Ondoka'],
  'Minimize': ['ചെറുതാക്കുക', 'Cheruthakkuka', 'Punguza'],
  'Full screen': ['മുഴുവൻ സ്ക്രീൻ', 'Muzhuvan screen', 'Skrini nzima'],
  'Add Video': ['വീഡിയോ ചേർക്കുക', 'Video cherkuka', 'Ongeza video'],
  'YouTube Link': ['യൂട്യൂബ് ലിങ്ക്', 'YouTube link', 'Kiungo cha YouTube'],
  'Live Doodle Together': ['തത്സമയം ഒരുമിച്ച് വരയ്ക്കാം', 'Thalsamayam orumichu varaykkam', 'Choreni pamoja mubashara'],
  'Draw': ['വരയ്ക്കുക', 'Varaykkuka', 'Chora'],
  'Brush': ['ബ്രഷ്', 'Brush', 'Brashi'],
  'Eraser': ['മായ്ക്കാൻ', 'Maykkan', 'Kifutio'],
  'Color': ['നിറം', 'Niram', 'Rangi'],
  'Size': ['വലുപ്പം', 'Valuppam', 'Ukubwa'],
  'Undo': ['പഴയപടിയാക്കുക', 'Pazhayapadiyakkuka', 'Tengua'],
  'Redo': ['വീണ്ടും ചെയ്യുക', 'Veendum cheyyuka', 'Rudia'],
  'Clear Canvas': ['ചിത്രം മായ്ക്കുക', 'Chithram maykkuka', 'Futa mchoro'],
  'Clear': ['മായ്ക്കുക', 'Maykkuka', 'Futa'],
  'Save': ['സൂക്ഷിക്കുക', 'Sookshikkuka', 'Hifadhi'],
  'Download': ['ഡൗൺലോഡ് ചെയ്യുക', 'Download cheyyuka', 'Pakua'],
  'Share': ['പങ്കിടുക', 'Pankiduka', 'Shiriki'],
  'Copy': ['പകർത്തുക', 'Pakarthuka', 'Nakili'],
  'Copied!': ['പകർത്തി!', 'Pakarthi!', 'Imenakiliwa!'],
  'Reset': ['ആദ്യപടിയിലേക്ക്', 'Aadyapadiyilekku', 'Weka upya'],
  'Cancel': ['റദ്ദാക്കുക', 'Raddakkuka', 'Ghairi'],
  'Delete': ['നീക്കുക', 'Neekkuka', 'Futa'],
  'Edit': ['തിരുത്തുക', 'Thiruthuka', 'Hariri'],
  'Add': ['ചേർക്കുക', 'Cherkkuka', 'Ongeza'],
  'Create': ['സൃഷ്ടിക്കുക', 'Srishtikkuka', 'Unda'],
  'Submit': ['സമർപ്പിക്കുക', 'Samarppikkuka', 'Wasilisha'],
  'Done': ['പൂർത്തിയായി', 'Poorthiyayi', 'Imekamilika'],
  'Close': ['അടയ്ക്കുക', 'Adaykkuka', 'Funga'],
  'Loading…': ['ലോഡ് ചെയ്യുന്നു…', 'Load cheyyunnu…', 'Inapakia…'],
  'Loading...': ['ലോഡ് ചെയ്യുന്നു…', 'Load cheyyunnu…', 'Inapakia…'],
  'Retry': ['വീണ്ടും ശ്രമിക്കുക', 'Veendum shramikkuka', 'Jaribu tena'],
  'Record': ['റെക്കോർഡ് ചെയ്യുക', 'Record cheyyuka', 'Rekodi'],
  'Stop Recording': ['റെക്കോർഡിംഗ് നിർത്തുക', 'Recording nirthuka', 'Acha kurekodi'],
  'Preview': ['മുൻകാഴ്ച', 'Munkazhcha', 'Hakiki'],
  'Apply': ['ഉപയോഗിക്കുക', 'Upayogikkuka', 'Tumia'],
  'Send': ['അയക്കുക', 'Ayakkuka', 'Tuma'],
  'Photos': ['ഫോട്ടോകൾ', 'Photokal', 'Picha'],
  'Videos': ['വീഡിയോകൾ', 'Videokal', 'Video'],
  'Memories': ['ഓർമ്മകൾ', 'Ormakal', 'Kumbukumbu'],
  'All Memories': ['എല്ലാ ഓർമ്മകളും', 'Ella ormakalum', 'Kumbukumbu zote'],
  'No Memories Found': ['ഓർമ്മകളൊന്നും കണ്ടെത്തിയില്ല', 'Ormakalonnum kandethiyilla', 'Hakuna kumbukumbu zilizopatikana'],
  'Shared Media Vault': ['പങ്കിട്ട ഓർമ്മകളുടെ ശേഖരം', 'Pankitta ormakalude shekharam', 'Hifadhi ya picha na video'],
  'Polaroid Memory Album': ['പോളറോയ്ഡ് ഓർമ്മ ആൽബം', 'Polaroid orma album', 'Albamu ya kumbukumbu za polaroid'],
  'Add First Memory': ['ആദ്യ ഓർമ്മ ചേർക്കുക', 'Aadya orma cherkkuka', 'Ongeza kumbukumbu ya kwanza'],
  'Add First Milestone': ['ആദ്യ നാഴികക്കല്ല് ചേർക്കുക', 'Aadya nazhikakkallu cherkkuka', 'Ongeza hatua muhimu ya kwanza'],
  'Timeline': ['ഓർമ്മകളുടെ കാലക്രമം', 'Ormakalude kalakramam', 'Mfululizo wa kumbukumbu'],
  'Milestones': ['നാഴികക്കല്ലുകൾ', 'Nazhikakkallukal', 'Hatua muhimu'],
  'Title': ['തലക്കെട്ട്', 'Thalakkettu', 'Kichwa'],
  'Description': ['വിവരണം', 'Vivaranam', 'Maelezo'],
  'Date': ['തീയതി', 'Theeyathi', 'Tarehe'],
  'Time': ['സമയം', 'Samayam', 'Saa'],
  'Category': ['വിഭാഗം', 'Vibhagam', 'Kategoria'],
  'Occasion': ['വിശേഷ ദിവസം', 'Vishesha divasam', 'Tukio'],
  'Seal Capsule': ['ഓർമ്മപ്പെട്ടി അടയ്ക്കുക', 'Ormappetti adaykkuka', 'Funga sanduku'],
  'Open Capsule': ['ഓർമ്മപ്പെട്ടി തുറക്കുക', 'Ormappetti thurakkuka', 'Fungua sanduku'],
  'Sealed': ['അടച്ചിരിക്കുന്നു', 'Adachirikkunnu', 'Limefungwa'],
  'Locked': ['പൂട്ടിയിരിക്കുന്നു', 'Poottiyirikkunnu', 'Limefungwa'],
  'Future': ['ഭാവി', 'Bhavi', 'Baadaye'],
  'Reveal': ['തുറന്നു കാണുക', 'Thurannu kanuka', 'Fichua'],
  'Love Coupons': ['കരുതലിന്റെ കൂപ്പണുകൾ', 'Karuthalinte couponukal', 'Kuponi za kujali'],
  'Couple Bucket List': ['ഒരുമിച്ച് ചെയ്യേണ്ട കാര്യങ്ങൾ', 'Orumichu cheyyenda karyangal', 'Orodha ya mambo ya kufanya pamoja'],
  'Surprise Date Night Wheel': ['സർപ്രൈസ് കൂടിക്കാഴ്ച ചക്രം', 'Surprise koodikkazhcha chakram', 'Gurudumu la matembezi ya mshangao'],
  'Spin': ['കറക്കുക', 'Karakkuka', 'Zungusha'],
  'Spin the Wheel': ['ചക്രം കറക്കുക', 'Chakram karakkuka', 'Zungusha gurudumu'],
  'Mark Complete': ['പൂർത്തിയായതായി അടയാളപ്പെടുത്തുക', 'Poorthiyayathayi adayalappeduthuka', 'Weka alama ya kukamilika'],
  'Completed': ['പൂർത്തിയായി', 'Poorthiyayi', 'Imekamilika'],
  'Redeem': ['ഉപയോഗിക്കുക', 'Upayogikkuka', 'Tumia kuponi'],
  'Battery Care Details': ['ബാറ്ററി കരുതൽ വിവരങ്ങൾ', 'Battery karuthal vivarangal', 'Maelezo ya utunzaji wa betri'],
  'Charging': ['ചാർജ് ചെയ്യുന്നു', 'Charge cheyyunnu', 'Inachaji'],
  'Live Location': ['തത്സമയ ലൊക്കേഷൻ', 'Thalsamaya location', 'Mahali ulipo sasa'],
  'Share Location': ['ലൊക്കേഷൻ പങ്കിടുക', 'Location pankiduka', 'Shiriki mahali ulipo'],
  'Stop Sharing': ['പങ്കിടൽ നിർത്തുക', 'Pankidal nirthuka', 'Acha kushiriki'],
  'Arrived': ['എത്തിച്ചേർന്നു', 'Ethichernnu', 'Nimefika'],
  'Sleep Together': ['ഒരുമിച്ച് വിശ്രമിക്കാം', 'Orumichu vishramikkam', 'Pumzikeni pamoja'],
  'Sleep Timer': ['വിശ്രമ ടൈമർ', 'Vishrama timer', 'Kipima muda cha kupumzika'],
  'Ambient Soundscapes': ['ചുറ്റുപാടിന്റെ ശബ്ദങ്ങൾ', 'Chuttupadinte shabdangal', 'Sauti za mazingira'],
  'AI Love Poetry & Letter Polisher ✍️💌': ['കുറിപ്പുകളും കവിതകളും എഴുതാൻ സഹായി ✍️💌', 'Kurippukalum kavithakalum ezhuthan sahayi ✍️💌', 'Msaidizi wa mashairi na barua ✍️💌'],
  'Generate': ['സൃഷ്ടിക്കുക', 'Srishtikkuka', 'Tengeneza'],
  'Regenerate': ['വീണ്ടും സൃഷ്ടിക്കുക', 'Veendum srishtikkuka', 'Tengeneza tena'],
  'Use in Chat': ['ചാറ്റിൽ ഉപയോഗിക്കുക', 'Chatil upayogikkuka', 'Tumia kwenye mazungumzo'],
  'Language': ['ഭാഷ', 'Bhasha', 'Lugha'],
  'Tone': ['ഭാവം', 'Bhavam', 'Hisia'],
  'Voice Note Duet 🎙️🎶': ['വോയ്സ് നോട്ട് ഡ്യുയറ്റ് 🎙️🎶', 'Voice note duet 🎙️🎶', 'Dueti ya ujumbe wa sauti 🎙️🎶'],
  'Hang out': ['ഒരുമിച്ച് സമയം ചെലവഴിക്കാം', 'Orumichu samayam chelavazhikkam', 'Pamoja'],
  'Make memories': ['ഓർമ്മകൾ സൃഷ്ടിക്കാം', 'Ormakal srishtikkam', 'Tengeneza kumbukumbu'],
  'Show up': ['കൂടെ നിൽക്കാം', 'Koode nilkkam', 'Kuwa karibu'],
  'Chat essentials': ['ചാറ്റ് സൗകര്യങ്ങൾ', 'Chat saukaryangal', 'Zana za mazungumzo'],
  'LITTLE THINGS. BIG FRIENDSHIP.': ['ചെറിയ കാര്യങ്ങൾ. വലിയ സൗഹൃദം.', 'Cheriya karyangal. Valiya sauhridam.', 'Mambo madogo. Urafiki mkubwa.'],
  'More ways to': ['കൂടെ നിൽക്കാൻ', 'Koode nilkkan', 'Njia zaidi za'],
  'be there.': ['കൂടുതൽ വഴികൾ.', 'kooduthal vazhikal.', 'kuwa karibu.'],
  'Your friendship toolkit': ['നിങ്ങളുടെ സൗഹൃദ കൂട്ടുപെട്ടി', 'Ningalude sauhrida koottupetti', 'Zana za urafiki wenu'],
  'Daily check-in': ['ഇന്നത്തെ വിശേഷം', 'Innathe vishesham', 'Hali ya leo'],
  'One question. A little closer.': ['ഒരു ചോദ്യം. കുറച്ചുകൂടി അടുത്ത്.', 'Oru chodyam. Kurachukoodi aduthu.', 'Swali moja. Karibu zaidi.'],
  'Listen together': ['ഒരുമിച്ച് കേൾക്കാം', 'Orumichu kelkkam', 'Sikilizeni pamoja'],
  'Your songs, in the same moment.': ['നിങ്ങളുടെ പാട്ടുകൾ, ഒരേ നിമിഷത്തിൽ.', 'Ningalude pattukal, ore nimishathil.', 'Nyimbo zenu, wakati mmoja.'],
  'Game night': ['കളിസമയം', 'Kalisamayam', 'Usiku wa michezo'],
  'Trivia, laughs, and friendly rivalry.': ['ചോദ്യങ്ങളും ചിരിയും സൗഹൃദ മത്സരവും.', 'Chodyangalum chiriyum sauhrida malsaravum.', 'Maswali, vicheko na ushindani wa kirafiki.'],
  'Watch party': ['ഒരുമിച്ച് കാണാം', 'Orumichu kanam', 'Tazameni pamoja'],
  'Press play and watch side by side.': ['പ്ലേ അമർത്തൂ, ഒന്നിച്ച് കാണാം.', 'Play amarthoo, onnichu kanam.', 'Bonyeza cheza na mtazame pamoja.'],
  'Doodle together': ['ഒരുമിച്ച് വരയ്ക്കാം', 'Orumichu varaykkam', 'Choreni pamoja'],
  'Make a wonderfully messy masterpiece.': ['കുത്തിവരകളിൽ ഒരു കിടിലൻ സൃഷ്ടി.', 'Kuthivarakalil oru kidilan srishti.', 'Undeni mchoro wa kufurahisha.'],
  'Voice duet': ['ശബ്ദ ഡ്യുയറ്റ്', 'Shabda duet', 'Dueti ya sauti'],
  'Two voices. One shared soundtrack.': ['രണ്ടു ശബ്ദങ്ങൾ. ഒരു പാട്ട്.', 'Randu shabdangal. Oru pattu.', 'Sauti mbili. Wimbo mmoja.'],
  'Memory scrapbook': ['ഓർമ്മപ്പുസ്തകം', 'Ormappusthakam', 'Albamu ya kumbukumbu'],
  'Keep the moments worth coming back to.': ['വീണ്ടും ഓർക്കാൻ ഇഷ്ടമുള്ള നിമിഷങ്ങൾ സൂക്ഷിക്കാം.', 'Veendum orkan ishtamulla nimishangal sookshikkam.', 'Hifadhi nyakati unazopenda kukumbuka.'],
  'Our story': ['നമ്മുടെ കഥ', 'Nammude katha', 'Hadithi yetu'],
  'Milestones in your friendship journey.': ['നിങ്ങളുടെ സൗഹൃദത്തിലെ പ്രധാന നാഴികക്കല്ലുകൾ.', 'Ningalude sauhridathile pradhana nazhikakkallukal.', 'Hatua muhimu katika urafiki wenu.'],
  'Time capsule': ['ഭാവിയിലേക്കുള്ള ഓർമ്മപ്പെട്ടി', 'Bhaviyilekkulla ormappetti', 'Sanduku la kumbukumbu za baadaye'],
  'A little surprise for your future selves.': ['ഭാവിയിലെ നിങ്ങൾക്കൊരു ചെറിയ സമ്മാനം.', 'Bhaviyile ningalkkoru cheriya sammanam.', 'Mshangao mdogo kwa ajili yenu baadaye.'],
  'Month in review': ['ഈ മാസത്തെ ഓർമ്മകൾ', 'Ee masathe ormakal', 'Kumbukumbu za mwezi'],
  'Turn your shared moments into a story.': ['ഒന്നിച്ചുള്ള നിമിഷങ്ങളെ ഒരു കഥയാക്കാം.', 'Onnichulla nimishangale oru kathayakkam.', 'Geuza nyakati zenu kuwa hadithi.'],
  'Send a hug': ['ഒരു ആലിംഗനം അയക്കാം', 'Oru alinganam ayakkam', 'Tuma kumbatio'],
  'A small touch to say “I’m here.”': ['“ഞാൻ കൂടെയുണ്ട്” എന്ന് പറയാൻ ഒരു ചെറിയ സ്പർശം.', '“Njan koodeyundu” ennu parayan oru cheriya sparsham.', 'Mguso mdogo wa kusema “Niko hapa.”'],
  'Live heartbeat': ['തത്സമയ ഹൃദയമിടിപ്പ്', 'Thalsamaya hridayamidippu', 'Mapigo ya moyo mubashara'],
  'Feel a little closer, wherever you are.': ['എവിടെയായാലും കുറച്ചുകൂടി അടുത്തറിയാം.', 'Evideyayalum kurachukoodi aduthariyam.', 'Jisikieni karibu zaidi, popote mlipo.'],
  'Little surprises': ['ചെറിയ സർപ്രൈസുകൾ', 'Cheriya surprises', 'Mishangao midogo'],
  'Thoughtful notes and kindness coupons.': ['ഹൃദ്യമായ കുറിപ്പുകളും കരുതലിന്റെ കൂപ്പണുകളും.', 'Hridyamaya kurippukalum karuthalinte couponukalum.', 'Ujumbe wa kujali na kuponi za fadhili.'],
  'On my way': ['ഞാൻ വരുന്ന വഴിയിലാണ്', 'Njan varunna vazhiyilanu', 'Niko njiani'],
  'Share your live location and arrival time.': ['തത്സമയ ലൊക്കേഷനും എത്തുന്ന സമയവും പങ്കിടാം.', 'Thalsamaya locationum ethunna samayavum pankidam.', 'Shiriki mahali ulipo na muda wa kufika.'],
  'Battery care': ['ബാറ്ററി കരുതൽ', 'Battery karuthal', 'Utunzaji wa betri'],
  'A friendly reminder to stay charged.': ['ചാർജ് ചെയ്യാൻ ഒരു സൗഹൃദ ഓർമ്മപ്പെടുത്തൽ.', 'Charge cheyyan oru sauhrida ormappeduthal.', 'Kikumbusho cha kirafiki cha kuchaji.'],
  'Wind down together': ['ഒരുമിച്ച് വിശ്രമിക്കാം', 'Orumichu vishramikkam', 'Pumzikeni pamoja'],
  'A shared, peaceful space for the night.': ['രാത്രിയിൽ ഒന്നിച്ച് ശാന്തമായി വിശ്രമിക്കാം.', 'Rathriyil onnichu shanthamayi vishramikkam.', 'Nafasi ya amani ya pamoja kwa usiku.'],
  'A note from the heart': ['ഹൃദയത്തിൽ നിന്നൊരു കുറിപ്പ്', 'Hridayathil ninnoru kurippu', 'Ujumbe kutoka moyoni'],
  'Find the words for what you want to say.': ['പറയാനുള്ളതിന് അനുയോജ്യമായ വാക്കുകൾ കണ്ടെത്താം.', 'Parayanullathinu anuyojyamaya vakkukal kandetham.', 'Pata maneno ya kusema unachohisi.'],
  'Invisible ink': ['രഹസ്യ മഷി', 'Rahasya mashi', 'Wino usioonekana'],
  'Hide a message behind a little magic.': ['ഒരു ചെറിയ മായാജാലത്തിൽ സന്ദേശം മറയ്ക്കാം.', 'Oru cheriya mayajalathil sandesham maraykkam.', 'Ficha ujumbe nyuma ya uchawi mdogo.'],
  'Scheduled messages': ['സമയമിട്ട് അയക്കുന്ന സന്ദേശങ്ങൾ', 'Samayamittu ayakkunna sandeshangal', 'Ujumbe uliopangwa'],
  'Send a thought at just the right time.': ['കൃത്യമായ സമയത്ത് ഒരു ചിന്ത അയക്കാം.', 'Krithyamaya samayathu oru chintha ayakkam.', 'Tuma wazo kwa wakati unaofaa.'],
  'Starred messages': ['പ്രിയപ്പെട്ട സന്ദേശങ്ങൾ', 'Priyappetta sandeshangal', 'Ujumbe uliowekewa nyota'],
  'Your favorite words, saved for later.': ['പ്രിയപ്പെട്ട വാക്കുകൾ പിന്നീട് വായിക്കാൻ സൂക്ഷിക്കാം.', 'Priyappetta vakkukal pinneedu vayikkan sookshikkam.', 'Maneno unayopenda, yamehifadhiwa kwa baadaye.'],
  'Pinned messages': ['പിൻ ചെയ്ത സന്ദേശങ്ങൾ', 'Pin cheytha sandeshangal', 'Ujumbe uliobandikwa'],
  'Keep the important things close.': ['പ്രധാനപ്പെട്ട കാര്യങ്ങൾ കൈയെത്തും ദൂരത്ത്.', 'Pradhanappetta karyangal kayyethum doorathu.', 'Weka mambo muhimu karibu.'],
  'Search this chat': ['ഈ ചാറ്റിൽ തിരയാം', 'Ee chatil thirayam', 'Tafuta kwenye mazungumzo haya'],
  'Find that thing you said that one time.': ['അന്ന് പറഞ്ഞ കാര്യം വീണ്ടും കണ്ടെത്താം.', 'Annu paranja karyam veendum kandetham.', 'Pata kile mlichosema wakati ule.'],
  'Shared files': ['പങ്കിട്ട ഫയലുകൾ', 'Pankitta fileukal', 'Faili zilizoshirikiwa'],
  'All your photos and documents in one place.': ['എല്ലാ ഫോട്ടോകളും രേഖകളും ഒരിടത്ത്.', 'Ella photokalum rekhakalum oridathu.', 'Picha na nyaraka zenu zote mahali pamoja.'],
  'Disappearing messages': ['തനിയെ മായുന്ന സന്ദേശങ്ങൾ', 'Thaniye mayunna sandeshangal', 'Ujumbe unaotoweka'],
  'Choose how long new messages stay.': ['പുതിയ സന്ദേശങ്ങൾ എത്രനേരം നിലനിൽക്കണമെന്ന് തിരഞ്ഞെടുക്കാം.', 'Puthiya sandeshangal ethraneram nilanilkkanamennu thiranjedukkam.', 'Chagua muda wa ujumbe mpya kubaki.'],
  'Export chat': ['ചാറ്റ് ഡൗൺലോഡ് ചെയ്യാം', 'Chat download cheyyam', 'Pakua mazungumzo'],
  'Download a copy of your conversation.': ['നിങ്ങളുടെ സംഭാഷണത്തിന്റെ പകർപ്പ് ഡൗൺലോഡ് ചെയ്യാം.', 'Ningalude sambhashanathinte pakarppu download cheyyam.', 'Pakua nakala ya mazungumzo yenu.'],
  'Group settings': ['ഗ്രൂപ്പ് ക്രമീകരണങ്ങൾ', 'Group kramikaranangal', 'Mipangilio ya kikundi'],
  'Manage your people and group details.': ['അംഗങ്ങളെയും ഗ്രൂപ്പ് വിവരങ്ങളെയും നിയന്ത്രിക്കാം.', 'Angangaleyum group vivarangaleyum niyanthrikkam.', 'Dhibiti wanachama na taarifa za kikundi.'],
  'Block or report user': ['ഉപയോക്താവിനെ ബ്ലോക്ക് ചെയ്യുക അല്ലെങ്കിൽ റിപ്പോർട്ട് ചെയ്യുക', 'Userine block cheyyuka allenkil report cheyyuka', 'Zuia au ripoti mtumiaji'],
  'Manage this contact and your boundaries.': ['ഈ കോൺടാക്ടും നിങ്ങളുടെ സ്വകാര്യതയും നിയന്ത്രിക്കാം.', 'Ee contactum ningalude swakaryathayum niyanthrikkam.', 'Dhibiti mtu huyu na mipaka yako.'],
  'Make it yours': ['നിങ്ങൾക്കിഷ്ടമുള്ള രീതിയിൽ', 'Ningalkkishtamulla reethiyil', 'Ifanye iwe yako'],
  'Themes, reading size, and your profile.': ['തീമുകൾ, അക്ഷരവലുപ്പം, നിങ്ങളുടെ പ്രൊഫൈൽ.', 'Themukal, aksharavalu ppam, ningalude profile.', 'Mandhari, ukubwa wa maandishi na wasifu wako.'],
  'Disguise mode': ['വേഷംമാറിയ മോഡ്', 'Veshamariya mode', 'Hali ya kujificha'],
  'Switch to your discreet calculator view.': ['കാൽക്കുലേറ്റർ കാഴ്ചയിലേക്ക് മാറാം.', 'Calculator kazhchayilekku maram.', 'Badili hadi mwonekano wa kikokotoo.'],
  'Choose a conversation to begin': ['തുടങ്ങാൻ ഒരു സംഭാഷണം തിരഞ്ഞെടുക്കുക', 'Thudangan oru sambhashanam thiranjedukkuka', 'Chagua mazungumzo ili kuanza'],
  'Unavailable while this contact is blocked': ['ഈ കോൺടാക്ട് ബ്ലോക്ക് ചെയ്തിരിക്കുമ്പോൾ ലഭ്യമല്ല', 'Ee contact block cheythirikkumbol labhyamalla', 'Haipatikani mtu huyu akiwa amezuiwa'],
  'Available in one-to-one friendships': ['രണ്ടുപേർ തമ്മിലുള്ള ചാറ്റിൽ ലഭ്യമാണ്', 'Randuper thammilulla chatil labhyamanu', 'Inapatikana katika mazungumzo ya watu wawili'],
  'Reconnect to start this activity': ['ഈ പ്രവർത്തനം തുടങ്ങാൻ വീണ്ടും കണക്റ്റ് ചെയ്യുക', 'Ee pravarthanam thudangan veendum connect cheyyuka', 'Unganisha tena ili kuanza shughuli hii'],
  'Finish your message first': ['ആദ്യം നിങ്ങളുടെ സന്ദേശം പൂർത്തിയാക്കുക', 'Aadyam ningalude sandesham poorthiyakkuka', 'Maliza ujumbe wako kwanza'],
  'No features found': ['സൗകര്യങ്ങളൊന്നും കണ്ടെത്തിയില്ല', 'Saukaryangalonnum kandethiyilla', 'Hakuna zana zilizopatikana'],
  'Try another word or explore a different category.': ['മറ്റൊരു വാക്കോ വിഭാഗമോ പരീക്ഷിക്കുക.', 'Mattoru vakko vibhagamo pareekshikkuka.', 'Jaribu neno lingine au kategoria nyingine.'],
  'Make a moment': ['ഒരു നിമിഷം ഒരുക്കാം', 'Oru nimisham orukkam', 'Tengeneza wakati mzuri'],
  'Same team.': ['ഒരേ ടീം.', 'Ore team.', 'Timu moja.'],
  'Every day.': ['എല്ലാ ദിവസവും.', 'Ella divasavum.', 'Kila siku.'],
  'Our little world': ['നമ്മുടെ ചെറിയ ലോകം', 'Nammude cheriya lokam', 'Dunia yetu ndogo'],
  'How is your heart today?': ['ഇന്ന് നിങ്ങളുടെ മനസ്സ് എങ്ങനെയുണ്ട്?', 'Innu ningalude manassu enganeyundu?', 'Unajisikiaje leo?'],
  'Happy': ['സന്തോഷം', 'Santhosham', 'Furaha'],
  'Tired': ['ക്ഷീണം', 'Ksheenam', 'Uchovu'],
  'Missing You': ['നിന്നെ മിസ് ചെയ്യുന്നു', 'Ninne miss cheyyunnu', 'Ninakukosa'],
  'Need a Hug': ['ഒരു ആലിംഗനം വേണം', 'Oru alinganam venam', 'Nahitaji kumbatio'],
  'No check-in yet': ['ഇനിയും വിശേഷം പറഞ്ഞിട്ടില്ല', 'Iniyum vishesham paranjittilla', 'Bado hakuna hali iliyoshirikiwa'],
  'You': ['നിങ്ങൾ', 'Ningal', 'Wewe'],
  'Visible for 24 hours': ['24 മണിക്കൂർ കാണാം', '24 manikkoor kanam', 'Inaonekana kwa saa 24'],
  'One little tap to feel a little closer.': ['ഒരു ചെറിയ ടാപ്പ്, കുറച്ചുകൂടി അടുത്ത്.', 'Oru cheriya tap, kurachukoodi aduthu.', 'Mguso mmoja mdogo, karibu zaidi.'],
  'Sender’s original message': ['അയച്ചയാളുടെ യഥാർത്ഥ സന്ദേശം', 'Ayachayalude yathartha sandesham', 'Ujumbe halisi wa mtumaji'],
  'Translated message': ['പരിഭാഷപ്പെടുത്തിയ സന്ദേശം', 'Paribhashappeduthiya sandesham', 'Ujumbe uliotafsiriwa'],
  'Translating… · Original shown': ['പരിഭാഷപ്പെടുത്തുന്നു… · യഥാർത്ഥ സന്ദേശം കാണിക്കുന്നു', 'Paribhashappeduthunnu… · Yathartha sandesham kanikkunnu', 'Inatafsiriwa… · Ujumbe halisi umeonyeshwa'],
  'Translation unavailable · Retry': ['പരിഭാഷ ലഭ്യമല്ല · വീണ്ടും ശ്രമിക്കുക', 'Paribhasha labhyamalla · Veendum shramikkuka', 'Tafsiri haipatikani · Jaribu tena'],
};

export function localFeatureCopy(text, language) {
  if (language === 'en') return text;
  const item = featureCopy[normalizeFeatureText(text)];
  return item?.[FEATURE_LANGUAGES.indexOf(language) - 1] || null;
}
